import { Bot, CircleCheckBig, Coins, Shield, Zap } from "lucide-react";

const Feature = () => {

  const features = [
    {
      title: "Real-Time Competition",
      description: "Battle head-to-head against other developers in live coding challenges that simulates real interview pressure",
      icon: <Zap className="bg-transparent" width={20} height={20} />
    },
    {
      title: "Unique Challenges",
      description: "Face unique problems generated by AI that prevents memorized solutions and keep you on your toes",
      icon: <Bot className="bg-transparent" width={20} height={20} />
    },
    {
      title: "Token Rewards",
      description: "Win tokens for successfull solutions that you can exchange for real rewards - practice with actual stakes",
      icon: <Coins className="bg-transparent" width={20} height={20} />
    },
    {
      title: "Anti-Cheat System",
      description: "Compete with confidence knowing our advanced system ensures fair play for all participants",
      icon: <Shield className="bg-transparent" width={20} height={20} />
    },
    {
      title: "Instant Feedback",
      description: "Get immediate results through automated test cases to quickly improve your coding skills",
      icon: <CircleCheckBig className="bg-transparent" width={20} height={20} />
    },
    {
      title: "Performance Analytic",
      description: "Track your progress with detailed metrics and identify areas for improvement",
      icon: <Bot className="bg-transparent" width={20} height={20} />
    }
  ]
  return (
    <section id="features" className="mx-auto w-fit my-12">
      <h3 className="text-[38px] font-bold text-gray-300">
        Practice Like It&apos;s The Real Thing
      </h3>
      <p className="text-gray-400">Experience the pressure of technical interview in a competitive environment designed to help you succeed</p>
      <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 p-4">
        {features.map(({ title, description, icon }, id) => <li key={id} className=" text-white p-4 rounded flex gap-4">
          <div className="bg-[#1e293b] p-1 aspect-square rounded-full h-6 w-6 flex justify-center items-center">
            {icon}
          </div>
          <div className="flex flex-col gap-2">
            <h5>{title}</h5>
            <p className="leading-4">{description}</p>
          </div>
        </li>)}
      </ul>
    </section>
  )
}
export default Feature;
